name: Aprendiendo GitHub Actions
run-name:  Estoy aprendiendo Github Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Definir variable de entorno
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python holamundo.py
